spring.application.name=Spring_CollegePratical_Project
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=manager


server.servlet.context-path=/code

server.port=8088


spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update



